
/**************************************************************
 *	
 *	bg, 8 bit, 11025Hz,
 *	1 channel, 673344 bytes/channel
 *	Total Size: 1 * 673344 + 4 (header) = 673388 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/nishatfiroj/CS2261/FINAL/bg.wav
 *	Time-stamp: Thu Nov 29 20:07:39 2018
 *	
 **************************************************************/

#ifndef __BGH__
#define __BGH__

#define BGFREQ 11025
#define BGLEN 673344

extern const unsigned char bg[673344];

#endif /* __BGH__ */
