
/**************************************************************
 *	
 *	hiss, 8 bit, 44100Hz,
 *	1 channel, 81232 bytes/channel
 *	Total Size: 1 * 81232 + 4 (header) = 81276 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/nishatfiroj/CS2261/FINAL/hiss.wav
 *	Time-stamp: Mon Dec 03 15:35:08 2018
 *	
 **************************************************************/

#ifndef __HISSH__
#define __HISSH__

#define HISSFREQ 44100
#define HISSLEN 81232

extern const unsigned char hiss[81232];

#endif /* __HISSH__ */
