
/**************************************************************
 *	
 *	ohno, 8 bit, 11025Hz,
 *	1 channel, 14400 bytes/channel
 *	Total Size: 1 * 14400 + 4 (header) = 14444 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/nishatfiroj/CS2261/FINAL/ohno.wav
 *	Time-stamp: Thu Nov 29 21:29:29 2018
 *	
 **************************************************************/

#ifndef __OHNOH__
#define __OHNOH__

#define OHNOFREQ 11025
#define OHNOLEN 14400

extern const unsigned char ohno[14400];

#endif /* __OHNOH__ */
