
/**************************************************************
 *	
 *	thud, 8 bit, 11025Hz,
 *	1 channel, 1889 bytes/channel
 *	Total Size: 1 * 1889 + 4 (header) = 1933 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/nishatfiroj/CS2261/FINAL/thud.wav
 *	Time-stamp: Sun Dec 02 19:21:56 2018
 *	
 **************************************************************/

#ifndef __THUDH__
#define __THUDH__

#define THUDFREQ 11025
#define THUDLEN 1889

extern const unsigned char thud[1889];

#endif /* __THUDH__ */
